image: node:10.15.0

services:
  - postgres:10.5

stages:
  - build
  - test
  - deploy

# This folder is cached between builds
cache:
  paths:
  - node_modules/

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.14.0

build:
  stage: build
  script:
   - yarn install

test_async:
  stage: test
  script:
   - yarn test

deploy to heroku:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --api-key=$HEROKU_API_KEY --app=dikaeinstein-graphql-api
