image: node:10.15.0

services:
  - postgres:10.5
  
variables:
  POSTGRES_DB: $DATABASE_test
  POSTGRES_USER: $DB_USERNAME
  POSTGRES_PASSWORD: $DB_PASSWORD

stages:
  - build
  - test

# This folder is cached between builds
cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
   - yarn install

test_async:
  stage: test
  script:
   - yarn test
