image: node:10.15.0

services:
  - postgres:10.5

stage:
  - build
  - test

# This folder is cached between builds
cache:
  paths:
  - node_modules/

before_script:
  - psql -c 'create database user_messages_test;' -U postgres

build:
  stage: build
  script:
   - yarn install

test_async:
  stage: test
  script:
   - yarn test
