image: node:10.15.0

services:
  - postgres:10.5

stages:
  - build
  - test

# This folder is cached between builds
cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
   - yarn install

test_async:
  stage: test
  before_script:
    - psql -c 'create database user_messages_test;' -h postgres -U postgres
  script:
   - yarn test
